Repository PestisCorp/Pestis, pull requests merged in 2025-02, with the labels that each got.

#75 54 population model
  Pestis/Assets/NuGet.config
  Pestis/Assets/NuGet.config.meta
  Pestis/Assets/NuGet.meta
  Pestis/Assets/NuGet/Editor.meta
  Pestis/Assets/NuGet/Editor/NuGetForUnity.PluginAPI.dll
  Pestis/Assets/NuGet/Editor/NuGetForUnity.PluginAPI.dll.meta
  Pestis/Assets/NuGet/Editor/NuGetForUnity.PluginAPI.xml
  Pestis/Assets/NuGet/Editor/NuGetForUnity.PluginAPI.xml.meta
  Pestis/Assets/NuGet/Editor/NugetForUnity.dll
  Pestis/Assets/NuGet/Editor/NugetForUnity.dll.meta
  Pestis/Assets/NuGet/LICENSE
  Pestis/Assets/NuGet/LICENSE.meta
  Pestis/Assets/NuGet/README.pdf
  Pestis/Assets/NuGet/README.pdf.meta
  Pestis/Assets/NuGet/Resources.meta
  Pestis/Assets/NuGet/Resources/defaultIcon.png
  Pestis/Assets/NuGet/Resources/defaultIcon.png.meta
  Pestis/Assets/Packages.meta
  Pestis/Assets/Scripts/Horde/PopulationController.cs
  Pestis/Assets/Scripts/Population.meta
  Pestis/Assets/Scripts/Population/markov.jl
  Pestis/Assets/Scripts/Population/markov.jl.meta
  Pestis/Assets/packages.config
  Pestis/Assets/packages.config.meta
Labels: enhancement, design

#96 Minor WebGL perf improvements
  Pestis/Assets/Scenes/NetworkedMap.unity
  Pestis/Assets/Scripts/Map/MapBehaviour.cs
  Pestis/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset.meta
  Pestis/Assets/Tilesets/Tileset.spriteatlasv2
  Pestis/Assets/Tilesets/Tileset.spriteatlasv2.meta
  Pestis/ProjectSettings/ProjectSettings.asset
Labels: performance

#97 Initial mutation system
  Pestis/Assets/Prefabs/PlayerControlled/RatBaseCamp.prefab
  Pestis/Assets/Prefabs/PlayerControlled/RatHorde.prefab
  Pestis/Assets/Prefabs/UI.meta
  Pestis/Assets/Prefabs/UI/PassiveMutationNotificationPrefab.prefab
  Pestis/Assets/Prefabs/UI/PassiveMutationNotificationPrefab.prefab.meta
  Pestis/Assets/Scenes/NetworkedMap.unity
  Pestis/Assets/Scripts/Horde/EvolutionManager.cs
  Pestis/Assets/Scripts/Horde/HordeController.cs
  Pestis/Assets/Scripts/Horde/PopulationController.cs
  Pestis/Assets/Scripts/Horde/RatController.cs
  Pestis/Assets/Scripts/UI/UI_manager.cs
  Pestis/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#91 added color change to the horde respawned
  Pestis/Assets/Scenes/NetworkedMap.unity
  Pestis/Assets/Scripts/GameManager.cs
  Pestis/Assets/Scripts/GameManager.cs.meta
  Pestis/Assets/Scripts/Horde/HordeController.cs
  Pestis/Assets/Scripts/Players/Player.cs
Labels: enhancement

#109 103 fix cheese rate
  Pestis/Assets/Scripts/Players/Player.cs
Labels: enhancement
