Repository PestisCorp/Pestis, pull requests merged in 2025-03, with the labels that each got.

#149 tweaked POI distances, adjusted the size of POIs
  Pestis/Assets/Scripts/BiomeClass.cs
  Pestis/Assets/Scripts/Map/MapGenerator.cs
  Pestis/Assets/charactor_design.meta
  Pestis/Assets/charactor_design/archive.meta
  Pestis/Assets/charactor_design/rat.meta
Labels: bug

#164 Fix freeze bug
  Pestis/Assets/Scripts/Horde/EvolutionManager.cs
Labels: bug

#165 Battle start effect
  Pestis/Assets/Audio/SFX/Event_raidhorn4.ogg
  Pestis/Assets/Audio/SFX/Event_raidhorn4.ogg.meta
  Pestis/Assets/Audio/SFX/Pillager_death1.ogg
  Pestis/Assets/Audio/SFX/Pillager_death1.ogg.meta
  Pestis/Assets/Audio/SFX/Pufferfish_flop1.ogg
  Pestis/Assets/Audio/SFX/Pufferfish_flop1.ogg.meta
  Pestis/Assets/Audio/SFX/Vote_started.wav
  Pestis/Assets/Audio/SFX/Vote_started.wav.meta
  Pestis/Assets/CombatFXManager.cs
  Pestis/Assets/CombatFXManager.cs.meta
  Pestis/Assets/Prefabs/POI/City.prefab
  Pestis/Assets/Prefabs/POI/Farm.prefab
  Pestis/Assets/Prefabs/POI/Lab.prefab
  Pestis/Assets/Prefabs/POI/human_camp.prefab
  Pestis/Assets/Prefabs/PlayerControlled/RatHorde.prefab
  Pestis/Assets/Scripts/Horde/CombatController.cs
  Pestis/Assets/Scripts/Horde/HordeController.cs
  Pestis/Assets/Scripts/InputHandler.cs
  Pestis/Assets/Sprites/combat effects.meta
  Pestis/Assets/Sprites/vfx.meta
  Pestis/Assets/Sprites/vfx/battlesmoke.aseprite
  Pestis/Assets/Sprites/vfx/battlesmoke.aseprite.meta
  Pestis/Assets/Sprites/vfx/marksaseprite.aseprite
  Pestis/Assets/Sprites/vfx/marksaseprite.aseprite.meta
Labels: enhancement

#195 UI highlighting
  Pestis/Assets/Prefabs/UI/DarkScreenCanvas.prefab
  Pestis/Assets/Prefabs/UI/DarkScreenCanvas.prefab.meta
  Pestis/Assets/Prefabs/UI/StartMenu.prefab
  Pestis/Assets/Scripts/Players/HumanPlayer.cs
  Pestis/Assets/Scripts/UI/UI_manager.cs
Labels: enhancement

#230 Capture effect bug
  Pestis/Assets/Prefabs/POI/City.prefab
  Pestis/Assets/Prefabs/POI/Farm.prefab
  Pestis/Assets/Prefabs/POI/Lab.prefab
  Pestis/Assets/Prefabs/POI/Van.prefab
  Pestis/Assets/Prefabs/POI/human_camp.prefab
  Pestis/Assets/Scripts/POI/POIController.cs
Labels: bug

#237 Improve boid performance with large number of hordes
  Pestis/Assets/Audio/Music/The Snowfield March.wav.meta
  Pestis/Assets/Audio/SFX/Event_raidhorn4.ogg.meta
  Pestis/Assets/Audio/SFX/Pillager_death1.ogg.meta
  Pestis/Assets/Audio/SFX/Pufferfish_flop1.ogg.meta
  Pestis/Assets/Audio/SFX/Vote_started.wav.meta
  Pestis/Assets/Photon/Fusion/Resources/NetworkProjectConfig.fusion
  Pestis/Assets/Scripts/GameManager.cs
  Pestis/Assets/Scripts/Horde/CombatBoids.cs
  Pestis/Assets/Scripts/Horde/HordeController.cs
  Pestis/Assets/Scripts/Horde/RatBoids.cs
  Pestis/Assets/Scripts/Human/HumanBoids.cs
  Pestis/Assets/Scripts/Human/PatrolController.cs
  Pestis/Assets/Scripts/Networking/PlayerSpawner.cs
  Pestis/Assets/Scripts/Players/BotPlayer.cs
  Pestis/Assets/Scripts/Players/Player.cs
  Pestis/Assets/Shaders/rats.compute
  Pestis/Assets/UniversalRenderPipelineGlobalSettings.asset
Labels: performance

#251 sound only plays for local player's hordes
  Pestis/Assets/Prefabs/PlayerControlled/RatHorde.prefab
  Pestis/Assets/Scripts/CombatFXManager.cs
Labels: bug

#259 Network and GPU optimisation
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Common.dll
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Common.dll.debug
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Common.pdb.debug
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Realtime.dll
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Realtime.dll.debug
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Realtime.pdb.debug
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Runtime.dll
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Runtime.dll.debug
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Runtime.pdb.debug
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Sockets.dll
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Sockets.dll.debug
  Pestis/Assets/Photon/Fusion/Assemblies/Fusion.Sockets.pdb.debug
  Pestis/Assets/Prefabs/Combat/CombatController.prefab
  Pestis/Assets/Prefabs/POI/City.prefab
  Pestis/Assets/Prefabs/POI/Farm.prefab
  Pestis/Assets/Prefabs/POI/Lab.prefab
  Pestis/Assets/Prefabs/POI/Van.prefab
  Pestis/Assets/Prefabs/POI/human_camp.prefab
  Pestis/Assets/Prefabs/PlayerControlled/BotBaseCamp.prefab
  Pestis/Assets/Prefabs/PlayerControlled/RatBaseCamp.prefab
  Pestis/Assets/Prefabs/PlayerControlled/RatHorde.prefab
  Pestis/Assets/Prefabs/SessionManager.prefab
  Pestis/Assets/Scripts/CombatFXManager.cs
  Pestis/Assets/Scripts/GameManager.cs
  Pestis/Assets/Scripts/Horde/AbilityController.cs
  Pestis/Assets/Scripts/Horde/CombatBoids.cs
  Pestis/Assets/Scripts/Horde/CombatController.cs
  Pestis/Assets/Scripts/Horde/EvolutionManager.cs
  Pestis/Assets/Scripts/Horde/HordeController.cs
  Pestis/Assets/Scripts/Horde/PopulationController.cs
  Pestis/Assets/Scripts/Horde/RatBoids.cs
  Pestis/Assets/Scripts/Horde/RatController.cs
  Pestis/Assets/Scripts/Horde/RatController.cs.meta
  Pestis/Assets/Scripts/InputHandler.cs
  Pestis/Assets/Scripts/Networking/SessionManager.cs
  Pestis/Assets/Scripts/Networking/Types.cs
  Pestis/Assets/Scripts/Networking/Types.cs.meta
  Pestis/Assets/Scripts/Players/Player.cs
  Pestis/Assets/Scripts/UI/HordeSplitManager.cs
  Pestis/Assets/Scripts/UI/UI_manager.cs
  Pestis/Assets/Shaders/combatRats.compute
  Pestis/Assets/Shaders/rats.compute
  Pestis/Assets/UniversalRenderPipelineGlobalSettings.asset
  Pestis/ProjectSettings/AudioManager.asset
  Pestis/ProjectSettings/ProjectSettings.asset
Labels: performance

#261 Mutation fixes
  Pestis/Assets/Prefabs/UI/AbilityToolbar.prefab
  Pestis/Assets/Prefabs/UI/Mutation_canvas.prefab
  Pestis/Assets/Prefabs/UI/mutation_text.prefab
  Pestis/Assets/Resources/PerformanceTestRunInfo.json
  Pestis/Assets/Resources/PerformanceTestRunInfo.json.meta
  Pestis/Assets/Resources/PerformanceTestRunSettings.json
  Pestis/Assets/Resources/PerformanceTestRunSettings.json.meta
  Pestis/Assets/Resources/UI_design/Mutations/MAD_btn.png
  Pestis/Assets/Resources/UI_design/Mutations/MAD_btn.png.meta
  Pestis/Assets/Resources/UI_design/Mutations/apparition_btn.png
  Pestis/Assets/Resources/UI_design/Mutations/apparition_btn.png.meta
  Pestis/Assets/Resources/UI_design/Mutations/corpsebloom_btn.png
  Pestis/Assets/Resources/UI_design/Mutations/corpsebloom_btn.png.meta
  Pestis/Assets/Resources/UI_design/Mutations/pestis_btn.png
  Pestis/Assets/Resources/UI_design/Mutations/pestis_btn.png.meta
  Pestis/Assets/Resources/UI_design/Mutations/poltergeist_btn.png
  Pestis/Assets/Resources/UI_design/Mutations/poltergeist_btn.png.meta
  Pestis/Assets/Resources/UI_design/Mutations/sewer_dwellers_btn.png
  Pestis/Assets/Resources/UI_design/Mutations/sewer_dwellers_btn.png.meta
  Pestis/Assets/Resources/active_mutations.json
  Pestis/Assets/Scripts/Horde/AbilityController.cs
  Pestis/Assets/Scripts/Horde/EvolutionManager.cs
  Pestis/Assets/Scripts/Horde/HordeController.cs
  Pestis/Assets/Scripts/Horde/PopulationController.cs
  Pestis/Assets/Scripts/Horde/RatBoids.cs
  Pestis/Assets/Scripts/Panner.cs
  Pestis/Assets/Scripts/Players/Player.cs
  Pestis/Assets/Scripts/UI/HordeSplitManager.cs
  Pestis/Assets/Scripts/UI/StartMenu.cs
  Pestis/Assets/Scripts/UI/UI_manager.cs
Labels: bug

#270 Fix POIs not capturing on non-master client, fix mutations not being being taken by combat victor
  Pestis/Assets/Resources/PerformanceTestRunInfo.json
  Pestis/Assets/Resources/PerformanceTestRunInfo.json.meta
  Pestis/Assets/Resources/PerformanceTestRunSettings.json
  Pestis/Assets/Resources/PerformanceTestRunSettings.json.meta
  Pestis/Assets/Scripts/Combat/CombatController.cs
  Pestis/Assets/Scripts/GameManager.cs
  Pestis/Assets/Scripts/Horde/EvolutionManager.cs
  Pestis/Assets/Scripts/Horde/HordeController.cs
  Pestis/Assets/Scripts/Horde/RatBoids.cs
  Pestis/Assets/Scripts/Human/PatrolController.cs
  Pestis/Assets/Scripts/POI/POIController.cs
  Pestis/Assets/UniversalRenderPipelineGlobalSettings.asset
Labels: bug

#267 Humans respawn on a POI if it's not been controlled for a while
  Pestis/Assets/Map.meta
  Pestis/Assets/Map/map.map.meta
  Pestis/Assets/Scripts/Human/PatrolController.cs
  Pestis/Assets/Scripts/Human/humans.compute
  Pestis/Assets/Scripts/POI/POIController.cs
  Pestis/Assets/UniversalRenderPipelineGlobalSettings.asset
Labels: enhancement, QOL
